[project]
name = "pulumi-autodoc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.30",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]
